#!/usr/bin/bash

# This script requires sed and awk, neither of which exist on the default
# nix-based librelane docker instance. To install them, do something like:
#
#     nix-env --install --attr nixpkgs.gawk
#     which awk  #==> "/root/.nix-profile/bin/awk"
#     
#     nix-env --install --attr nixpkgs.gnused
#     which sed  #==> "/root/.nix-profile/bin/sed"

function result0 { awk '/Passed/{printf " "p}{p=$NF}' $1 | cut -b 2-; }
function getrun { echo -n runs/; grep -m 1 RUN $1 | tr "'." ' ' | xargs -n 1 | grep RUN; }
function latest { \ls -d $1/* | grep "$2" | tail -1; }
function getclk0 { awk '/^clk/{print $2;exit}' $(latest $1 dpnr)/clock.rpt; }
function critpath0 { cat $(latest $1 dpnr)/max.rpt | awk '/arrival/{print $1;exit}'; }

function lastword { cat $1 | xargs -n 1 | tail -1; }
function setup0 { lastword $(latest $1 dpnr)/ws.max.rpt; }
function hold0  { lastword $(latest $1 dpnr)/ws.min.rpt; }

sedwarn='/flow.py/d;s/    .*//;s/.........../    /;s/ in the following.*//'
sederr='/^\[/{tag=$2}/violation/ && tag~/ERROR/{$1=$1; print $0}'
function getwarn { egrep 'WARNING.*violations' $1 | sed "$sedwarn"; }
function geterr { awk "$sederr" $1 | sed 's/ in the following.*//'; }
function viol { echo $(setup0 $1) | awk '$1 >= 0 { exit 13 }'; }

for log in $*; do
    run=$(getrun $log)
    echo $log $run; cd $(dirname $log)
    res=$(result0 $log)
    [ "$res" ] || printf "    FAILED\n\n"; [ "$res" ] || continue
    # run=runs/$(getrun $log)
    if test -d $run; then
      getclk0 $run   | awk '{printf("            Clock %5.1fns (%dMHz)\n", $1, 1000/$1)}'
      critpath0 $run | awk '{printf("    Critical path  %5.2fns\n", $1)}'
      printf "       Setup/Hold  %5.2fns %5.2fns\n" $(setup0 $run) $(hold0 $run)
    else
        echo "          WARNING  Cannot find run directory $run"
    fi
    getwarn $log | sed 's/^/      /'
    echo "           PASSED  $res"
    if viol $run;
        then printf "            ERROR  Setup violation %5.2fns\n" $(setup0 $run)
        else geterr $log | sed 's/^/            ERROR  /'
    fi
    echo ""
done
