function plotgraph(bit, Vth, Vdd)
    filename_b2 = ['FP-WlcBth2Sqr_', int2str(bit), '.csv'];
%          filename_b2= ['fp', int2str(bit), '_b2_res.csv'];
     filename_b3 = ['FP-WlcBth3Sqr_', int2str(bit), '.csv'];
     filename_bd = ['FP-design', int2str(bit), '.csv'];
%     filename_b3 = 'des_fp16_res.csv';

    [ mapped_d2, routed_d2, optimized_d2, mapped_p2, routed_p2, optimized_p2]...
        = readcsv(filename_b2, Vth, Vdd);
    [ mapped_d3, routed_d3, optimized_d3, mapped_p3, routed_p3, optimized_p3]...
        = readcsv(filename_b3, Vth, Vdd);
    [ mapped_dd, routed_dd, optimized_dd, mapped_pd, routed_pd, optimized_p3d]...
        = readcsv(filename_bd, Vth, Vdd);
    
%     mapped_p2= mapped_p2/1000;
%     routed_p2= routed_p2/1000;
%     optimized_p2 = optimized_p2/1000;

   plot(mapped_d2, mapped_p2,'-.rx',...
       optimized_d2, optimized_p2,'-rx',...
       routed_d2, routed_p2,'--rx',...
       mapped_d3, mapped_p3,'-.g^',...
       optimized_d3, optimized_p3,'-^g',...
       routed_d3, routed_p3,'--g^',...
       mapped_dd, mapped_pd,'-.bo',...
       routed_dd, routed_pd,'-bo',...
       'LineWidth',2,'MarkerSize',9);
   set(gca,'fontsize',12);
   title([int2str(bit),'bit Floating Point Wallace Multiplier'],'fontsize',18);
   
   xlabel('Delay (ns)','fontsize',18),grid
   ylabel('Dynamic Energy (pJ)','fontsize',18)
   legend('Booth2 - synthesized (no wires)', ...
       ['Booth2 - layout informed P&R'], ...
       'Booth2 - uninformed P&R', ...
       'Booth3 - synthesized (no wires)',...       
       ['Booth3 - layout informed P&R'], ...
       'Booth3 - uninformed P&R',...
              'Generic Library - synthesized (no wires)',...       
       'Generic Library - uninformed P&R'...
 ,'fontsize',14);
    

%      axis ([0.6 1.5 20 75]);
end
