function plotgraph(bit, Vth, Vdd)
    filename_b2 = ['FP-WlcBth2Sqr_', int2str(bit), '.csv'];
%          filename_b2= ['fp', int2str(bit), '_b2_res.csv'];
     filename_b3 = ['FP-WlcBth3Sqr_', int2str(bit), '.csv'];
     filename_b4 = ['FP-OS1cBth2Sqr_', int2str(bit), '.csv'];
     filename_bd = ['FP-design', int2str(bit), '.csv'];
%     filename_b3 = 'des_fp16_res.csv';

    filename_b5 = ['FP-WlcBth2Sqr_', int2str(bit), '_01112012.csv'];
    filename_b6 = ['FP-OS1cBth2Sqr_', int2str(bit), '_01122012.csv'];
    filename_b7 = ['FP-OS1cBth2Par_', int2str(bit), '_01112012.csv'];

    [ mapped_d2, routed_d2, optimized_d2, mapped_p2, routed_p2, optimized_p2]...
        = readcsv(filename_b2, Vth, Vdd);
    [ mapped_d3, routed_d3, optimized_d3, mapped_p3, routed_p3, optimized_p3]...
        = readcsv(filename_b3, Vth, Vdd);
    [ mapped_d4, routed_d4, optimized_d4, mapped_p4, routed_p4, optimized_p4]...
        = readcsv(filename_b4, Vth, Vdd);
    [ mapped_dd, routed_dd, optimized_dd, mapped_pd, routed_pd, optimized_p3d]...
        = readcsv(filename_bd, Vth, Vdd);

    [ mapped_d5, routed_d5, optimized_d5, mapped_p5, routed_p5, optimized_p5]...
        = readcsv(filename_b5, Vth, Vdd);
    [ mapped_d6, routed_d6, optimized_d6, mapped_p6, routed_p6, optimized_p6]...
        = readcsv(filename_b6, Vth, Vdd);
    
    [ mapped_d7, routed_d7, optimized_d7, mapped_p7, routed_p7, optimized_p7]...
        = readcsv(filename_b7, Vth, Vdd);
    
    
%     mapped_p2= mapped_p2/1000;
%     routed_p2= routed_p2/1000;
%     optimized_p2 = optimized_p2/1000;

%    plot(mapped_d2, mapped_p2,'-.rx',...
%        optimized_d2, optimized_p2,'-rx',...
%        routed_d2, routed_p2,'--rx',...
%        mapped_d3, mapped_p3,'-.g^',...
%        optimized_d3, optimized_p3,'-^g',...
%        routed_d3, routed_p3,'--g^',...
%        mapped_dd, mapped_pd,'-.bo',...
%        routed_dd, routed_pd,'-bo',...
%        mapped_d4, mapped_p4,'-.m*',...
%        optimized_d4, optimized_p4,'-m*',...
%        routed_d4, routed_p4,'--m*',...
%        'LineWidth',2,'MarkerSize',9);
%    set(gca,'fontsize',12);
%    title([int2str(bit),'bit Floating Point Wallace Multiplier'],'fontsize',18);
%    
%    xlabel('Delay (ns)','fontsize',18),grid
%    ylabel('Dynamic Energy (pJ)','fontsize',18)
%    legend('Booth2 - synthesized (no wires)', ...
%        ['Booth2 - layout informed P&R'], ...
%        'Booth2 - uninformed P&R', ...
%        'Booth3 - synthesized (no wires)',...       
%        ['Booth3 - layout informed P&R'], ...
%        'Booth3 - uninformed P&R',...
%               'Generic Library - synthesized (no wires)',...       
%        'Generic Library - uninformed P&R',...
%        'OS1 Booth2 - synthesized (no wires)', ...
%        ['OS1 Booth2 - layout informed P&R'], ...
%        'OS1 Booth2 - uninformed P&R' ...
%  ,'fontsize',14);
    

%      axis ([0.6 1.5 20 75]);






   plot(mapped_d5, mapped_p5,'-.rx',...
       optimized_d5, optimized_p5,'-rx',...
       routed_d5, routed_p5,'--rx',...
       mapped_d6, mapped_p6,'-.g^',...
       optimized_d6, optimized_p6,'-^g',...
       routed_d6, routed_p6,'--g^',...
       mapped_d7, mapped_p7,'-.bo',...
       optimized_d7, optimized_p7,'-bo',...
       routed_d7, routed_p7,'--bo',...       
       'LineWidth',2,'MarkerSize',9);
   set(gca,'fontsize',12);
   title([int2str(bit),'bit Floating Point Wallace & OS1 Multiplier from 01/11/2012'],'fontsize',18);
   
   xlabel('Delay (ns)','fontsize',18),grid
   ylabel('Dynamic Energy (pJ)','fontsize',18)
   legend('Wl Booth2 Sqr- synthesized (no wires)', ...
       ['Wl Booth2 Sqr- layout informed P&R'], ...
       'Wl Booth2 Sqr- uninformed P&R', ...
       'OS1 Booth2 Sqr- synthesized (no wires)', ...
       ['OS1 Booth2 Sqr- layout informed P&R'], ...
       'OS1 Booth2 Sqr- uninformed P&R', ...
       'OS1 Booth2 Par- synthesized (no wires)', ...
       ['OS1 Booth2 Par- layout informed P&R'], ...
       'OS1 Booth2 Par- uninformed P&R' ...
 ,'fontsize',14);
    

end
